"""The paths of the EN 16931 rules about the UBL document itself. Generated.

By `tools/ubl_syntax.py`, from the Schematron file at the version in
`published.SOURCES["en16931"]`. Do not edit by hand.

`ABSENT` has, for each rule that says an element or attribute is not to be
there, its path from the document's root (`//` is anywhere). `AT_MOST_ONE`
has, for each rule that says an element is there no more than once, the
element the rule is asked of and the path from it.

Licence
-------
These paths are not this project's. They are from the EN 16931 validation
artefacts, copyright their authors, and are under the European Union Public
Licence 1.2, whose text is beside this file in `LICENSE-EUPL-1.2.txt`. The
rest of this package is under the licence in its own LICENSE file.
"""

ABSENT = {
    'UBL-CR-001': 'ext:UBLExtensions',
    'UBL-CR-003': 'cbc:ProfileExecutionID',
    'UBL-CR-004': 'cbc:CopyIndicator',
    'UBL-CR-005': 'cbc:UUID',
    'UBL-CR-006': 'cbc:IssueTime',
    'UBL-CR-007': 'cbc:PricingCurrencyCode',
    'UBL-CR-008': 'cbc:PaymentCurrencyCode',
    'UBL-CR-009': 'cbc:PaymentAlternativeCurrencyCode',
    'UBL-CR-010': 'cbc:AccountingCostCode',
    'UBL-CR-011': 'cbc:LineCountNumeric',
    'UBL-CR-012': 'cac:InvoicePeriod/cbc:StartTime',
    'UBL-CR-013': 'cac:InvoicePeriod/cbc:EndTime',
    'UBL-CR-014': 'cac:InvoicePeriod/cbc:DurationMeasure',
    'UBL-CR-015': 'cac:InvoicePeriod/cbc:Description',
    'UBL-CR-016': 'cac:OrderReference/cbc:CopyIndicator',
    'UBL-CR-017': 'cac:OrderReference/cbc:UUID',
    'UBL-CR-018': 'cac:OrderReference/cbc:IssueDate',
    'UBL-CR-019': 'cac:OrderReference/cbc:IssueTime',
    'UBL-CR-020': 'cac:OrderReference/cbc:CustomerReference',
    'UBL-CR-021': 'cac:OrderReference/cbc:OrderTypeCode',
    'UBL-CR-022': 'cac:OrderReference/cac:DocumentReference',
    'UBL-CR-023': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:CopyIndicator',
    'UBL-CR-024': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:UUID',
    'UBL-CR-025': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:IssueTime',
    'UBL-CR-026': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:DocumentTypeCode',
    'UBL-CR-027': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:DocumentType',
    'UBL-CR-028': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:XPath',
    'UBL-CR-029': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:LanguageID',
    'UBL-CR-030': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:LocaleCode',
    'UBL-CR-031': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:VersionID',
    'UBL-CR-032': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-033': 'cac:BillingReference/cac:InvoiceDocumentReference/cbc:DocumentDescription',
    'UBL-CR-034': 'cac:BillingReference/cac:InvoiceDocumentReference/cac:Attachment',
    'UBL-CR-035': 'cac:BillingReference/cac:InvoiceDocumentReference/cac:ValidityPeriod',
    'UBL-CR-036': 'cac:BillingReference/cac:InvoiceDocumentReference/cac:IssuerParty',
    'UBL-CR-037': 'cac:BillingReference/cac:InvoiceDocumentReference/cac:ResultOfVerification',
    'UBL-CR-038': 'cac:BillingReference/cac:SelfBilledInvoiceDocumentReference',
    'UBL-CR-039': 'cac:BillingReference/cac:CreditNoteDocumentReference',
    'UBL-CR-040': 'cac:BillingReference/cac:SelfBilledCreditNoteDocumentReference',
    'UBL-CR-041': 'cac:BillingReference/cac:DebitNoteDocumentReference',
    'UBL-CR-042': 'cac:BillingReference/cac:ReminderDocumentReference',
    'UBL-CR-043': 'cac:BillingReference/cac:AdditionalDocumentReference',
    'UBL-CR-044': 'cac:BillingReference/cac:BillingReferenceLine',
    'UBL-CR-045': 'cac:DespatchDocumentReference/cbc:CopyIndicator',
    'UBL-CR-046': 'cac:DespatchDocumentReference/cbc:UUID',
    'UBL-CR-047': 'cac:DespatchDocumentReference/cbc:IssueDate',
    'UBL-CR-048': 'cac:DespatchDocumentReference/cbc:IssueTime',
    'UBL-CR-049': 'cac:DespatchDocumentReference/cbc:DocumentTypeCode',
    'UBL-CR-050': 'cac:DespatchDocumentReference/cbc:DocumentType',
    'UBL-CR-051': 'cac:DespatchDocumentReference/cbc:XPath',
    'UBL-CR-052': 'cac:DespatchDocumentReference/cbc:LanguageID',
    'UBL-CR-053': 'cac:DespatchDocumentReference/cbc:LocaleCode',
    'UBL-CR-054': 'cac:DespatchDocumentReference/cbc:VersionID',
    'UBL-CR-055': 'cac:DespatchDocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-056': 'cac:DespatchDocumentReference/cbc:DocumentDescription',
    'UBL-CR-057': 'cac:DespatchDocumentReference/cac:Attachment',
    'UBL-CR-058': 'cac:DespatchDocumentReference/cac:ValidityPeriod',
    'UBL-CR-059': 'cac:DespatchDocumentReference/cac:IssuerParty',
    'UBL-CR-060': 'cac:DespatchDocumentReference/cac:ResultOfVerification',
    'UBL-CR-061': 'cac:ReceiptDocumentReference/cbc:CopyIndicator',
    'UBL-CR-062': 'cac:ReceiptDocumentReference/cbc:UUID',
    'UBL-CR-063': 'cac:ReceiptDocumentReference/cbc:IssueDate',
    'UBL-CR-064': 'cac:ReceiptDocumentReference/cbc:IssueTime',
    'UBL-CR-065': 'cac:ReceiptDocumentReference/cbc:DocumentTypeCode',
    'UBL-CR-066': 'cac:ReceiptDocumentReference/cbc:DocumentType',
    'UBL-CR-067': 'cac:ReceiptDocumentReference/cbc:XPath',
    'UBL-CR-068': 'cac:ReceiptDocumentReference/cbc:LanguageID',
    'UBL-CR-069': 'cac:ReceiptDocumentReference/cbc:LocaleCode',
    'UBL-CR-070': 'cac:ReceiptDocumentReference/cbc:VersionID',
    'UBL-CR-071': 'cac:ReceiptDocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-072': 'cac:ReceiptDocumentReference/cbc:DocumentDescription',
    'UBL-CR-073': 'cac:ReceiptDocumentReference/cac:Attachment',
    'UBL-CR-074': 'cac:ReceiptDocumentReference/cac:ValidityPeriod',
    'UBL-CR-075': 'cac:ReceiptDocumentReference/cac:IssuerParty',
    'UBL-CR-076': 'cac:ReceiptDocumentReference/cac:ResultOfVerification',
    'UBL-CR-077': 'cac:StatementDocumentReference',
    'UBL-CR-078': 'cac:OriginatorDocumentReference/cbc:CopyIndicator',
    'UBL-CR-079': 'cac:OriginatorDocumentReference/cbc:UUID',
    'UBL-CR-080': 'cac:OriginatorDocumentReference/cbc:IssueDate',
    'UBL-CR-081': 'cac:OriginatorDocumentReference/cbc:IssueTime',
    'UBL-CR-082': 'cac:OriginatorDocumentReference/cbc:DocumentTypeCode',
    'UBL-CR-083': 'cac:OriginatorDocumentReference/cbc:DocumentType',
    'UBL-CR-084': 'cac:OriginatorDocumentReference/cbc:XPath',
    'UBL-CR-085': 'cac:OriginatorDocumentReference/cbc:LanguageID',
    'UBL-CR-086': 'cac:OriginatorDocumentReference/cbc:LocaleCode',
    'UBL-CR-087': 'cac:OriginatorDocumentReference/cbc:VersionID',
    'UBL-CR-088': 'cac:OriginatorDocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-089': 'cac:OriginatorDocumentReference/cbc:DocumentDescription',
    'UBL-CR-090': 'cac:OriginatorDocumentReference/cac:Attachment',
    'UBL-CR-091': 'cac:OriginatorDocumentReference/cac:ValidityPeriod',
    'UBL-CR-092': 'cac:OriginatorDocumentReference/cac:IssuerParty',
    'UBL-CR-093': 'cac:OriginatorDocumentReference/cac:ResultOfVerification',
    'UBL-CR-094': 'cac:ContractDocumentReference/cbc:CopyIndicator',
    'UBL-CR-095': 'cac:ContractDocumentReference/cbc:UUID',
    'UBL-CR-096': 'cac:ContractDocumentReference/cbc:IssueDate',
    'UBL-CR-097': 'cac:ContractDocumentReference/cbc:IssueTime',
    'UBL-CR-098': 'cac:ContractDocumentReference/cbc:DocumentTypeCode',
    'UBL-CR-099': 'cac:ContractDocumentReference/cbc:DocumentType',
    'UBL-CR-100': 'cac:ContractDocumentReference/cbc:XPath',
    'UBL-CR-101': 'cac:ContractDocumentReference/cbc:LanguageID',
    'UBL-CR-102': 'cac:ContractDocumentReference/cbc:LocaleCode',
    'UBL-CR-103': 'cac:ContractDocumentReference/cbc:VersionID',
    'UBL-CR-104': 'cac:ContractDocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-105': 'cac:ContractDocumentReference/cbc:DocumentDescription',
    'UBL-CR-106': 'cac:ContractDocumentReference/cac:Attachment',
    'UBL-CR-107': 'cac:ContractDocumentReference/cac:ValidityPeriod',
    'UBL-CR-108': 'cac:ContractDocumentReference/cac:IssuerParty',
    'UBL-CR-109': 'cac:ContractDocumentReference/cac:ResultOfVerification',
    'UBL-CR-110': 'cac:AdditionalDocumentReference/cbc:CopyIndicator',
    'UBL-CR-111': 'cac:AdditionalDocumentReference/cbc:UUID',
    'UBL-CR-112': 'cac:AdditionalDocumentReference/cbc:IssueDate',
    'UBL-CR-113': 'cac:AdditionalDocumentReference/cbc:IssueTime',
    'UBL-CR-114': 'cac:AdditionalDocumentReference/cbc:DocumentType',
    'UBL-CR-115': 'cac:AdditionalDocumentReference/cbc:XPath',
    'UBL-CR-116': 'cac:AdditionalDocumentReference/cbc:LanguageID',
    'UBL-CR-117': 'cac:AdditionalDocumentReference/cbc:LocaleCode',
    'UBL-CR-118': 'cac:AdditionalDocumentReference/cbc:VersionID',
    'UBL-CR-119': 'cac:AdditionalDocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-121': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:DocumentHash',
    'UBL-CR-122': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:HashAlgorithmMethod',
    'UBL-CR-123': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:ExpiryDate',
    'UBL-CR-124': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:ExpiryTime',
    'UBL-CR-125': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:MimeCode',
    'UBL-CR-126': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:FormatCode',
    'UBL-CR-127': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:EncodingCode',
    'UBL-CR-128': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:CharacterSetCode',
    'UBL-CR-129': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:FileName',
    'UBL-CR-130': 'cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference/cbc:Description',
    'UBL-CR-131': 'cac:AdditionalDocumentReference/cac:ValidityPeriod',
    'UBL-CR-132': 'cac:AdditionalDocumentReference/cac:IssuerParty',
    'UBL-CR-133': 'cac:AdditionalDocumentReference/cac:ResultOfVerification',
    'UBL-CR-134': 'cac:ProjectReference/cbc:UUID',
    'UBL-CR-135': 'cac:ProjectReference/cbc:IssueDate',
    'UBL-CR-136': 'cac:ProjectReference/cac:WorkPhaseReference',
    'UBL-CR-137': 'cac:Signature',
    'UBL-CR-138': 'cac:AccountingSupplierParty/cbc:CustomerAssignedAccountID',
    'UBL-CR-139': 'cac:AccountingSupplierParty/cbc:AdditionalAccountID',
    'UBL-CR-140': 'cac:AccountingSupplierParty/cbc:DataSendingCapability',
    'UBL-CR-141': 'cac:AccountingSupplierParty/cac:Party/cbc:MarkCareIndicator',
    'UBL-CR-142': 'cac:AccountingSupplierParty/cac:Party/cbc:MarkAttentionIndicator',
    'UBL-CR-143': 'cac:AccountingSupplierParty/cac:Party/cbc:WebsiteURI',
    'UBL-CR-144': 'cac:AccountingSupplierParty/cac:Party/cbc:LogoReferenceID',
    'UBL-CR-145': 'cac:AccountingSupplierParty/cac:Party/cbc:IndustryClassificationCode',
    'UBL-CR-146': 'cac:AccountingSupplierParty/cac:Party/cac:Language',
    'UBL-CR-147': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:ID',
    'UBL-CR-148': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:AddressTypeCode',
    'UBL-CR-149': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:AddressFormatCode',
    'UBL-CR-150': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:Postbox',
    'UBL-CR-151': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:Floor',
    'UBL-CR-152': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:Room',
    'UBL-CR-153': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:BlockName',
    'UBL-CR-154': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:BuildingName',
    'UBL-CR-155': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:BuildingNumber',
    'UBL-CR-156': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:InhouseMail',
    'UBL-CR-157': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:Department',
    'UBL-CR-158': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:MarkAttention',
    'UBL-CR-159': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:MarkCare',
    'UBL-CR-160': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:PlotIdentification',
    'UBL-CR-161': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:CitySubdivisionName',
    'UBL-CR-162': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:CountrySubentityCode',
    'UBL-CR-163': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:Region',
    'UBL-CR-164': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:District',
    'UBL-CR-165': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cbc:TimezoneOffset',
    'UBL-CR-166': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cac:Country/cbc:Name',
    'UBL-CR-167': 'cac:AccountingSupplierParty/cac:Party/cac:PostalAddress/cac:LocationCoordinate',
    'UBL-CR-168': 'cac:AccountingSupplierParty/cac:Party/cac:PhysicalLocation',
    'UBL-CR-169': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:RegistrationName',
    'UBL-CR-170': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:TaxLevelCode',
    'UBL-CR-171': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:ExemptionReasonCode',
    'UBL-CR-172': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:ExemptionReason',
    'UBL-CR-173': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cac:RegistrationAddress',
    'UBL-CR-174': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:Name',
    'UBL-CR-175': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:TaxTypeCode',
    'UBL-CR-176': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:CurrencyCode',
    'UBL-CR-177': 'cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cac:JurisdictionRegionAddress',
    'UBL-CR-178': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationDate',
    'UBL-CR-179': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationExpirationDate',
    'UBL-CR-180': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyLegalFormCode',
    'UBL-CR-181': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:SoleProprietorshipIndicator',
    'UBL-CR-182': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyLiquidationStatusCode',
    'UBL-CR-183': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:CorporateStockAmount',
    'UBL-CR-184': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:FullyPaidSharesIndicator',
    'UBL-CR-185': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cac:RegistrationAddress',
    'UBL-CR-186': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cac:CorporateRegistrationScheme',
    'UBL-CR-187': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cac:HeadOfficeParty',
    'UBL-CR-188': 'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cac:ShareholderParty',
    'UBL-CR-189': 'cac:AccountingSupplierParty/cac:Party/cac:Contact/cbc:ID',
    'UBL-CR-190': 'cac:AccountingSupplierParty/cac:Party/cac:Contact/cbc:Telefax',
    'UBL-CR-191': 'cac:AccountingSupplierParty/cac:Party/cac:Contact/cbc:Note',
    'UBL-CR-192': 'cac:AccountingSupplierParty/cac:Party/cac:Contact/cac:OtherCommunication',
    'UBL-CR-193': 'cac:AccountingSupplierParty/cac:Party/cac:Person',
    'UBL-CR-194': 'cac:AccountingSupplierParty/cac:Party/cac:AgentParty',
    'UBL-CR-195': 'cac:AccountingSupplierParty/cac:Party/cac:ServiceProviderParty',
    'UBL-CR-196': 'cac:AccountingSupplierParty/cac:Party/cac:PowerOfAttorney',
    'UBL-CR-197': 'cac:AccountingSupplierParty/cac:Party/cac:FinancialAccount',
    'UBL-CR-198': 'cac:AccountingSupplierParty/cac:DespatchContact',
    'UBL-CR-199': 'cac:AccountingSupplierParty/cac:AccountingContact',
    'UBL-CR-200': 'cac:AccountingSupplierParty/cac:SellerContact',
    'UBL-CR-201': 'cac:AccountingCustomerParty/cbc:CustomerAssignedAccountID',
    'UBL-CR-202': 'cac:AccountingCustomerParty/cbc:SupplierAssignedAccountID',
    'UBL-CR-203': 'cac:AccountingCustomerParty/cbc:AdditionalAccountID',
    'UBL-CR-204': 'cac:AccountingCustomerParty/cac:Party/cbc:MarkCareIndicator',
    'UBL-CR-205': 'cac:AccountingCustomerParty/cac:Party/cbc:MarkAttentionIndicator',
    'UBL-CR-206': 'cac:AccountingCustomerParty/cac:Party/cbc:WebsiteURI',
    'UBL-CR-207': 'cac:AccountingCustomerParty/cac:Party/cbc:LogoReferenceID',
    'UBL-CR-208': 'cac:AccountingCustomerParty/cac:Party/cbc:IndustryClassificationCode',
    'UBL-CR-209': 'cac:AccountingCustomerParty/cac:Party/cac:Language',
    'UBL-CR-210': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:ID',
    'UBL-CR-211': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:AddressTypeCode',
    'UBL-CR-212': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:AddressFormatCode',
    'UBL-CR-213': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:Postbox',
    'UBL-CR-214': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:Floor',
    'UBL-CR-215': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:Room',
    'UBL-CR-216': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:BlockName',
    'UBL-CR-217': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:BuildingName',
    'UBL-CR-218': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:BuildingNumber',
    'UBL-CR-219': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:InhouseMail',
    'UBL-CR-220': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:Department',
    'UBL-CR-221': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:MarkAttention',
    'UBL-CR-222': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:MarkCare',
    'UBL-CR-223': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:PlotIdentification',
    'UBL-CR-224': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:CitySubdivisionName',
    'UBL-CR-225': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:CountrySubentityCode',
    'UBL-CR-226': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:Region',
    'UBL-CR-227': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:District',
    'UBL-CR-228': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cbc:TimezoneOffset',
    'UBL-CR-229': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cac:Country/cbc:Name',
    'UBL-CR-230': 'cac:AccountingCustomerParty/cac:Party/cac:PostalAddress/cac:LocationCoordinate',
    'UBL-CR-231': 'cac:AccountingCustomerParty/cac:Party/cac:PhysicalLocation',
    'UBL-CR-232': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cbc:RegistrationName',
    'UBL-CR-233': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cbc:TaxLevelCode',
    'UBL-CR-234': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cbc:ExemptionReasonCode',
    'UBL-CR-235': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cbc:ExemptionReason',
    'UBL-CR-236': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cac:RegistrationAddress',
    'UBL-CR-237': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:Name',
    'UBL-CR-238': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:TaxTypeCode',
    'UBL-CR-239': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cbc:CurrencyCode',
    'UBL-CR-240': 'cac:AccountingCustomerParty/cac:Party/cac:PartyTaxScheme/cac:TaxScheme/cac:JurisdictionRegionAddress',
    'UBL-CR-241': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationDate',
    'UBL-CR-242': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationExpirationDate',
    'UBL-CR-243': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyLegalFormCode',
    'UBL-CR-244': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyLegalForm',
    'UBL-CR-245': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:SoleProprietorshipIndicator',
    'UBL-CR-246': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyLiquidationStatusCode',
    'UBL-CR-247': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CorporateStockAmount',
    'UBL-CR-248': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:FullyPaidSharesIndicator',
    'UBL-CR-249': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cac:RegistrationAddress',
    'UBL-CR-250': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cac:CorporateRegistrationScheme',
    'UBL-CR-251': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cac:HeadOfficeParty',
    'UBL-CR-252': 'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cac:ShareholderParty',
    'UBL-CR-253': 'cac:AccountingCustomerParty/cac:Party/cac:Contact/cbc:ID',
    'UBL-CR-254': 'cac:AccountingCustomerParty/cac:Party/cac:Contact/cbc:Telefax',
    'UBL-CR-255': 'cac:AccountingCustomerParty/cac:Party/cac:Contact/cbc:Note',
    'UBL-CR-256': 'cac:AccountingCustomerParty/cac:Party/cac:Contact/cac:OtherCommunication',
    'UBL-CR-257': 'cac:AccountingCustomerParty/cac:Party/cac:Person',
    'UBL-CR-258': 'cac:AccountingCustomerParty/cac:Party/cac:AgentParty',
    'UBL-CR-259': 'cac:AccountingCustomerParty/cac:Party/cac:ServiceProviderParty',
    'UBL-CR-260': 'cac:AccountingCustomerParty/cac:Party/cac:PowerOfAttorney',
    'UBL-CR-261': 'cac:AccountingCustomerParty/cac:Party/cac:FinancialAccount',
    'UBL-CR-262': 'cac:AccountingCustomerParty/cac:DeliveryContact',
    'UBL-CR-263': 'cac:AccountingCustomerParty/cac:AccountingContact',
    'UBL-CR-264': 'cac:AccountingCustomerParty/cac:BuyerContact',
    'UBL-CR-265': 'cac:PayeeParty/cbc:MarkCareIndicator',
    'UBL-CR-266': 'cac:PayeeParty/cbc:MarkAttentionIndicator',
    'UBL-CR-267': 'cac:PayeeParty/cbc:WebsiteURI',
    'UBL-CR-268': 'cac:PayeeParty/cbc:LogoReferenceID',
    'UBL-CR-269': 'cac:PayeeParty/cbc:EndpointID',
    'UBL-CR-270': 'cac:PayeeParty/cbc:IndustryClassificationCode',
    'UBL-CR-271': 'cac:PayeeParty/cac:Language',
    'UBL-CR-272': 'cac:PayeeParty/cac:PostalAddress',
    'UBL-CR-273': 'cac:PayeeParty/cac:PhysicalLocation',
    'UBL-CR-274': 'cac:PayeeParty/cac:PartyTaxScheme',
    'UBL-CR-275': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:RegistrationName',
    'UBL-CR-276': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:RegistrationDate',
    'UBL-CR-277': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:RegistrationExpirationDate',
    'UBL-CR-278': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:CompanyLegalFormCode',
    'UBL-CR-279': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:CompanyLegalForm',
    'UBL-CR-280': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:SoleProprietorshipIndicator',
    'UBL-CR-281': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:CompanyLiquidationStatusCode',
    'UBL-CR-282': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:CorporateStockAmount',
    'UBL-CR-283': 'cac:PayeeParty/cac:PartyLegalEntity/cbc:FullyPaidSharesIndicator',
    'UBL-CR-284': 'cac:PayeeParty/cac:PartyLegalEntity/cac:RegistrationAddress',
    'UBL-CR-285': 'cac:PayeeParty/cac:PartyLegalEntity/cac:CorporateRegistrationScheme',
    'UBL-CR-286': 'cac:PayeeParty/cac:PartyLegalEntity/cac:HeadOfficeParty',
    'UBL-CR-287': 'cac:PayeeParty/cac:PartyLegalEntity/cac:ShareholderParty',
    'UBL-CR-288': 'cac:PayeeParty/cac:Contact',
    'UBL-CR-289': 'cac:PayeeParty/cac:Person',
    'UBL-CR-290': 'cac:PayeeParty/cac:AgentParty',
    'UBL-CR-291': 'cac:PayeeParty/cac:ServiceProviderParty',
    'UBL-CR-292': 'cac:PayeeParty/cac:PowerOfAttorney',
    'UBL-CR-293': 'cac:PayeeParty/cac:FinancialAccount',
    'UBL-CR-294': 'cac:BuyerCustomerParty',
    'UBL-CR-295': 'cac:SellerSupplierParty',
    'UBL-CR-296': 'cac:TaxRepresentativeParty/cbc:MarkCareIndicator',
    'UBL-CR-297': 'cac:TaxRepresentativeParty/cbc:MarkAttentionIndicator',
    'UBL-CR-298': 'cac:TaxRepresentativeParty/cbc:WebsiteURI',
    'UBL-CR-299': 'cac:TaxRepresentativeParty/cbc:LogoReferenceID',
    'UBL-CR-300': 'cac:TaxRepresentativeParty/cbc:EndpointID',
    'UBL-CR-301': 'cac:TaxRepresentativeParty/cbc:IndustryClassificationCode',
    'UBL-CR-302': 'cac:TaxRepresentativeParty/cac:PartyIdentification',
    'UBL-CR-303': 'cac:TaxRepresentativeParty/cac:Language',
    'UBL-CR-304': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:ID',
    'UBL-CR-305': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:AddressTypeCode',
    'UBL-CR-306': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:AddressFormatCode',
    'UBL-CR-307': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:Postbox',
    'UBL-CR-308': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:Floor',
    'UBL-CR-309': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:Room',
    'UBL-CR-310': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:BlockName',
    'UBL-CR-311': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:BuildingName',
    'UBL-CR-312': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:BuildingNumber',
    'UBL-CR-313': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:InhouseMail',
    'UBL-CR-314': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:Department',
    'UBL-CR-315': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:MarkAttention',
    'UBL-CR-316': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:MarkCare',
    'UBL-CR-317': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:PlotIdentification',
    'UBL-CR-318': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:CitySubdivisionName',
    'UBL-CR-319': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:CountrySubentityCode',
    'UBL-CR-320': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:Region',
    'UBL-CR-321': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:District',
    'UBL-CR-322': 'cac:TaxRepresentativeParty/cac:PostalAddress/cbc:TimezoneOffset',
    'UBL-CR-323': 'cac:TaxRepresentativeParty/cac:PostalAddress/cac:Country/cbc:Name',
    'UBL-CR-324': 'cac:TaxRepresentativeParty/cac:PostalAddress/cac:LocationCoordinate',
    'UBL-CR-325': 'cac:TaxRepresentativeParty/cac:PhysicalLocation',
    'UBL-CR-326': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cbc:RegistrationName',
    'UBL-CR-327': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cbc:TaxLevelCode',
    'UBL-CR-328': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cbc:ExemptionReasonCode',
    'UBL-CR-329': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cbc:ExemptionReason',
    'UBL-CR-330': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cac:RegistrationAddress',
    'UBL-CR-331': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cac:TaxScheme/cbc:Name',
    'UBL-CR-332': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cac:TaxScheme/cbc:TaxTypeCode',
    'UBL-CR-333': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cac:TaxScheme/cbc:CurrencyCode',
    'UBL-CR-334': 'cac:TaxRepresentativeParty/cac:PartyTaxScheme/cac:TaxScheme/cac:JurisdictionRegionAddress',
    'UBL-CR-335': 'cac:TaxRepresentativeParty/cac:PartyLegalEntity',
    'UBL-CR-336': 'cac:TaxRepresentativeParty/cac:Contact',
    'UBL-CR-337': 'cac:TaxRepresentativeParty/cac:Person',
    'UBL-CR-338': 'cac:TaxRepresentativeParty/cac:AgentParty',
    'UBL-CR-339': 'cac:TaxRepresentativeParty/cac:ServiceProviderParty',
    'UBL-CR-340': 'cac:TaxRepresentativeParty/cac:PowerOfAttorney',
    'UBL-CR-341': 'cac:TaxRepresentativeParty/cac:FinancialAccount',
    'UBL-CR-342': 'cac:Delivery/cbc:ID',
    'UBL-CR-343': 'cac:Delivery/cbc:Quantity',
    'UBL-CR-344': 'cac:Delivery/cbc:MinimumQuantity',
    'UBL-CR-345': 'cac:Delivery/cbc:MaximumQuantity',
    'UBL-CR-346': 'cac:Delivery/cbc:ActualDeliveryTime',
    'UBL-CR-347': 'cac:Delivery/cbc:LatestDeliveryDate',
    'UBL-CR-348': 'cac:Delivery/cbc:LatestDeliveryTime',
    'UBL-CR-349': 'cac:Delivery/cbc:ReleaseID',
    'UBL-CR-350': 'cac:Delivery/cbc:TrackingID',
    'UBL-CR-351': 'cac:Delivery/cac:DeliveryLocation/cbc:Description',
    'UBL-CR-352': 'cac:Delivery/cac:DeliveryLocation/cbc:Conditions',
    'UBL-CR-353': 'cac:Delivery/cac:DeliveryLocation/cbc:CountrySubentity',
    'UBL-CR-354': 'cac:Delivery/cac:DeliveryLocation/cbc:CountrySubentityCode',
    'UBL-CR-355': 'cac:Delivery/cac:DeliveryLocation/cbc:LocationTypeCode',
    'UBL-CR-356': 'cac:Delivery/cac:DeliveryLocation/cbc:InformationURI',
    'UBL-CR-357': 'cac:Delivery/cac:DeliveryLocation/cbc:Name',
    'UBL-CR-358': 'cac:Delivery/cac:DeliveryLocation/cac:ValidityPeriod',
    'UBL-CR-359': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:ID',
    'UBL-CR-360': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:AddressTypeCode',
    'UBL-CR-361': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:AddressFormatCode',
    'UBL-CR-362': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:Postbox',
    'UBL-CR-363': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:Floor',
    'UBL-CR-364': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:Room',
    'UBL-CR-365': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:BlockName',
    'UBL-CR-366': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:BuildingName',
    'UBL-CR-367': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:BuildingNumber',
    'UBL-CR-368': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:InhouseMail',
    'UBL-CR-369': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:Department',
    'UBL-CR-370': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:MarkAttention',
    'UBL-CR-371': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:MarkCare',
    'UBL-CR-372': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:PlotIdentification',
    'UBL-CR-373': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:CitySubdivisionName',
    'UBL-CR-374': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:CountrySubentityCode',
    'UBL-CR-375': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:Region',
    'UBL-CR-376': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:District',
    'UBL-CR-377': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cbc:TimezoneOffset',
    'UBL-CR-378': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cac:Country/cbc:Name',
    'UBL-CR-379': 'cac:Delivery/cac:DeliveryLocation/cac:Address/cac:LocationCoordinate',
    'UBL-CR-380': 'cac:Delivery/cac:DeliveryLocation/cac:SubsidiaryLocation',
    'UBL-CR-381': 'cac:Delivery/cac:DeliveryLocation/cac:LocationCoordinate',
    'UBL-CR-382': 'cac:Delivery/cac:AlternativeDeliveryLocation',
    'UBL-CR-383': 'cac:Delivery/cac:RequestedDeliveryPeriod',
    'UBL-CR-384': 'cac:Delivery/cac:EstimatedDeliveryPeriod',
    'UBL-CR-385': 'cac:Delivery/cac:CarrierParty',
    'UBL-CR-386': 'cac:Delivery/cac:DeliveryParty/cbc:MarkCareIndicator',
    'UBL-CR-387': 'cac:Delivery/cac:DeliveryParty/cbc:MarkAttentionIndicator',
    'UBL-CR-388': 'cac:Delivery/cac:DeliveryParty/cbc:WebsiteURI',
    'UBL-CR-389': 'cac:Delivery/cac:DeliveryParty/cbc:LogoReferenceID',
    'UBL-CR-390': 'cac:Delivery/cac:DeliveryParty/cbc:EndpointID',
    'UBL-CR-391': 'cac:Delivery/cac:DeliveryParty/cbc:IndustryClassificationCode',
    'UBL-CR-392': 'cac:Delivery/cac:DeliveryParty/cac:PartyIdentification',
    'UBL-CR-393': 'cac:Delivery/cac:DeliveryParty/cac:Language',
    'UBL-CR-394': 'cac:Delivery/cac:DeliveryParty/cac:PostalAddress',
    'UBL-CR-395': 'cac:Delivery/cac:DeliveryParty/cac:PhysicalLocation',
    'UBL-CR-396': 'cac:Delivery/cac:DeliveryParty/cac:PartyTaxScheme',
    'UBL-CR-397': 'cac:Delivery/cac:DeliveryParty/cac:PartyLegalEntity',
    'UBL-CR-398': 'cac:Delivery/cac:DeliveryParty/cac:Contact',
    'UBL-CR-399': 'cac:Delivery/cac:DeliveryParty/cac:Person',
    'UBL-CR-400': 'cac:Delivery/cac:DeliveryParty/cac:AgentParty',
    'UBL-CR-401': 'cac:Delivery/cac:DeliveryParty/cac:ServiceProviderParty',
    'UBL-CR-402': 'cac:Delivery/cac:DeliveryParty/cac:PowerOfAttorney',
    'UBL-CR-403': 'cac:Delivery/cac:DeliveryParty/cac:FinancialAccount',
    'UBL-CR-404': 'cac:Delivery/cac:NotifyParty',
    'UBL-CR-405': 'cac:Delivery/cac:Despatch',
    'UBL-CR-406': 'cac:Delivery/cac:DeliveryTerms',
    'UBL-CR-407': 'cac:Delivery/cac:MinimumDeliveryUnit',
    'UBL-CR-408': 'cac:Delivery/cac:MaximumDeliveryUnit',
    'UBL-CR-409': 'cac:Delivery/cac:Shipment',
    'UBL-CR-410': 'cac:DeliveryTerms',
    'UBL-CR-411': 'cac:PaymentMeans/cbc:ID',
    'UBL-CR-413': 'cac:PaymentMeans/cbc:PaymentChannelCode',
    'UBL-CR-414': 'cac:PaymentMeans/cbc:InstructionID',
    'UBL-CR-415': 'cac:PaymentMeans/cac:CardAccount/cbc:CardTypeCode',
    'UBL-CR-416': 'cac:PaymentMeans/cac:CardAccount/cbc:ValidityStartDate',
    'UBL-CR-417': 'cac:PaymentMeans/cac:CardAccount/cbc:ExpiryDate',
    'UBL-CR-418': 'cac:PaymentMeans/cac:CardAccount/cbc:IssuerID',
    'UBL-CR-419': 'cac:PaymentMeans/cac:CardAccount/cbc:IssueNumberID',
    'UBL-CR-420': 'cac:PaymentMeans/cac:CardAccount/cbc:CV2ID',
    'UBL-CR-421': 'cac:PaymentMeans/cac:CardAccount/cbc:CardChipCode',
    'UBL-CR-422': 'cac:PaymentMeans/cac:CardAccount/cbc:ChipApplicationID',
    'UBL-CR-424': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:AliasName',
    'UBL-CR-425': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:AccountTypeCode',
    'UBL-CR-426': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:AccountFormatCode',
    'UBL-CR-427': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:CurrencyCode',
    'UBL-CR-428': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:PaymentNote',
    'UBL-CR-429': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cbc:Name',
    'UBL-CR-430': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:FinancialInstitution/cbc:Name',
    'UBL-CR-431': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:FinancialInstitution/cac:Address',
    'UBL-CR-432': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cac:Address',
    'UBL-CR-433': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cac:Country',
    'UBL-CR-434': 'cac:PaymentMeans/cac:CreditAccount',
    'UBL-CR-435': 'cac:PaymentMeans/cac:PaymentMandate/cbc:MandateTypeCode',
    'UBL-CR-436': 'cac:PaymentMeans/cac:PaymentMandate/cbc:MaximumPaymentInstructionsNumeric',
    'UBL-CR-437': 'cac:PaymentMeans/cac:PaymentMandate/cbc:MaximumPaidAmount',
    'UBL-CR-438': 'cac:PaymentMeans/cac:PaymentMandate/cbc:SignatureID',
    'UBL-CR-439': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerParty',
    'UBL-CR-440': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cbc:Name',
    'UBL-CR-441': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cbc:AliasName',
    'UBL-CR-442': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cbc:AccountTypeCode',
    'UBL-CR-443': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cbc:AccountFormatCode',
    'UBL-CR-444': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cbc:CurrencyCode',
    'UBL-CR-445': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cbc:PaymentNote',
    'UBL-CR-446': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cac:FinancialInstitutionBranch',
    'UBL-CR-447': 'cac:PaymentMeans/cac:PaymentMandate/cac:PayerFinancialAccount/cac:Country',
    'UBL-CR-448': 'cac:PaymentMeans/cac:PaymentMandate/cac:ValidityPeriod',
    'UBL-CR-449': 'cac:PaymentMeans/cac:PaymentMandate/cac:PaymentReversalPeriod',
    'UBL-CR-450': 'cac:PaymentMeans/cac:PaymentMandate/cac:Clause',
    'UBL-CR-451': 'cac:PaymentMeans/cac:TradeFinancing',
    'UBL-CR-452': 'cac:PaymentTerms/cbc:ID',
    'UBL-CR-453': 'cac:PaymentTerms/cbc:PaymentMeansID',
    'UBL-CR-454': 'cac:PaymentTerms/cbc:PrepaidPaymentReferenceID',
    'UBL-CR-455': 'cac:PaymentTerms/cbc:ReferenceEventCode',
    'UBL-CR-456': 'cac:PaymentTerms/cbc:SettlementDiscountPercent',
    'UBL-CR-457': 'cac:PaymentTerms/cbc:PenaltySurchargePercent',
    'UBL-CR-458': 'cac:PaymentTerms/cbc:PaymentPercent',
    'UBL-CR-459': 'cac:PaymentTerms/cbc:Amount',
    'UBL-CR-460': 'cac:PaymentTerms/cbc:SettlementDiscountAmount',
    'UBL-CR-461': 'cac:PaymentTerms/cbc:PenaltyAmount',
    'UBL-CR-462': 'cac:PaymentTerms/cbc:PaymentTermsDetailsURI',
    'UBL-CR-463': 'cac:PaymentTerms/cbc:PaymentDueDate',
    'UBL-CR-464': 'cac:PaymentTerms/cbc:InstallmentDueDate',
    'UBL-CR-465': 'cac:PaymentTerms/cbc:InvoicingPartyReference',
    'UBL-CR-466': 'cac:PaymentTerms/cac:SettlementPeriod',
    'UBL-CR-467': 'cac:PaymentTerms/cac:PenaltyPeriod',
    'UBL-CR-468': 'cac:PaymentTerms/cac:ExchangeRate',
    'UBL-CR-469': 'cac:PaymentTerms/cac:ValidityPeriod',
    'UBL-CR-470': 'cac:PrepaidPayment',
    'UBL-CR-471': 'cac:AllowanceCharge/cbc:ID',
    'UBL-CR-472': 'cac:AllowanceCharge/cbc:PrepaidIndicator',
    'UBL-CR-473': 'cac:AllowanceCharge/cbc:SequenceNumeric',
    'UBL-CR-474': 'cac:AllowanceCharge/cbc:AccountingCostCode',
    'UBL-CR-475': 'cac:AllowanceCharge/cbc:AccountingCost',
    'UBL-CR-476': 'cac:AllowanceCharge/cbc:PerUnitAmount',
    'UBL-CR-477': 'cac:AllowanceCharge/cac:TaxCategory/cbc:Name',
    'UBL-CR-478': 'cac:AllowanceCharge/cac:TaxCategory/cbc:BaseUnitMeasure',
    'UBL-CR-479': 'cac:AllowanceCharge/cac:TaxCategory/cbc:PerUnitAmount',
    'UBL-CR-480': 'cac:AllowanceCharge/cac:TaxCategory/cbc:TaxExemptionReasonCode',
    'UBL-CR-481': 'cac:AllowanceCharge/cac:TaxCategory/cbc:TaxExemptionReason',
    'UBL-CR-482': 'cac:AllowanceCharge/cac:TaxCategory/cbc:TierRange',
    'UBL-CR-483': 'cac:AllowanceCharge/cac:TaxCategory/cbc:TierRatePercent',
    'UBL-CR-484': 'cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cbc:Name',
    'UBL-CR-485': 'cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cbc:TaxTypeCode',
    'UBL-CR-486': 'cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cbc:CurrencyCode',
    'UBL-CR-487': 'cac:AllowanceCharge/cac:TaxCategory/cac:TaxScheme/cac:JurisdictionRegionAddress',
    'UBL-CR-488': 'cac:AllowanceCharge/cac:TaxTotal',
    'UBL-CR-489': 'cac:AllowanceCharge/cac:PaymentMeans',
    'UBL-CR-490': 'cac:TaxExchangeRate',
    'UBL-CR-491': 'cac:PricingExchangeRate',
    'UBL-CR-492': 'cac:PaymentExchangeRate',
    'UBL-CR-493': 'cac:PaymentAlternativeExchangeRate',
    'UBL-CR-494': 'cac:TaxTotal/cbc:RoundingAmount',
    'UBL-CR-495': 'cac:TaxTotal/cbc:TaxEvidenceIndicator',
    'UBL-CR-496': 'cac:TaxTotal/cbc:TaxIncludedIndicator',
    'UBL-CR-497': 'cac:TaxTotal/cac:TaxSubtotal/cbc:CalculationSequenceNumeric',
    'UBL-CR-498': 'cac:TaxTotal/cac:TaxSubtotal/cbc:TransactionCurrencyTaxAmount',
    'UBL-CR-499': 'cac:TaxTotal/cac:TaxSubtotal/cbc:Percent',
    'UBL-CR-500': 'cac:TaxTotal/cac:TaxSubtotal/cbc:BaseUnitMeasure',
    'UBL-CR-501': 'cac:TaxTotal/cac:TaxSubtotal/cbc:PerUnitAmount',
    'UBL-CR-502': 'cac:TaxTotal/cac:TaxSubtotal/cbc:TierRange',
    'UBL-CR-503': 'cac:TaxTotal/cac:TaxSubtotal/cbc:TierRatePercent',
    'UBL-CR-504': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:Name',
    'UBL-CR-505': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:BaseUnitMeasure',
    'UBL-CR-506': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:PerUnitAmount',
    'UBL-CR-507': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:TierRange',
    'UBL-CR-508': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cbc:TierRatePercent',
    'UBL-CR-509': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cac:TaxScheme/cbc:Name',
    'UBL-CR-510': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cac:TaxScheme/cbc:TaxTypeCode',
    'UBL-CR-511': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cac:TaxScheme/cbc:CurrencyCode',
    'UBL-CR-512': 'cac:TaxTotal/cac:TaxSubtotal/cac:TaxCategory/cac:TaxScheme/cac:JurisdictionRegionAddress',
    'UBL-CR-513': 'cac:WithholdingTaxTotal',
    'UBL-CR-514': 'cac:LegalMonetaryTotal/cbc:PayableAlternativeAmount',
    'UBL-CR-515': '(cac:InvoiceLine|cac:CreditNoteLine)/cbc:UUID',
    'UBL-CR-516': '(cac:InvoiceLine|cac:CreditNoteLine)/cbc:TaxPointDate',
    'UBL-CR-517': '(cac:InvoiceLine|cac:CreditNoteLine)/cbc:AccountingCostCode',
    'UBL-CR-518': '(cac:InvoiceLine|cac:CreditNoteLine)/cbc:PaymentPurposeCode',
    'UBL-CR-519': '(cac:InvoiceLine|cac:CreditNoteLine)/cbc:FreeOfChargeIndicator',
    'UBL-CR-520': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:InvoicePeriod/cbc:StartTime',
    'UBL-CR-521': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:InvoicePeriod/cbc:EndTime',
    'UBL-CR-522': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:InvoicePeriod/cbc:DurationMeasure',
    'UBL-CR-523': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:InvoicePeriod/cbc:DescriptionCode',
    'UBL-CR-524': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:InvoicePeriod/cbc:Description',
    'UBL-CR-525': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:OrderLineReference/cbc:SalesOrderLineID',
    'UBL-CR-526': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:OrderLineReference/cbc:UUID',
    'UBL-CR-527': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:OrderLineReference/cbc:LineStatusCode',
    'UBL-CR-528': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:OrderLineReference/cac:OrderReference',
    'UBL-CR-529': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DespatchLineReference',
    'UBL-CR-530': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:ReceiptLineReference',
    'UBL-CR-531': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:BillingReference',
    'UBL-CR-532': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:CopyIndicator',
    'UBL-CR-533': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:UUID',
    'UBL-CR-534': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:IssueDate',
    'UBL-CR-535': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:IssueTime',
    'UBL-CR-537': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:DocumentType',
    'UBL-CR-538': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:XPath',
    'UBL-CR-539': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:LanguageID',
    'UBL-CR-540': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:LocaleCode',
    'UBL-CR-541': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:VersionID',
    'UBL-CR-542': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:DocumentStatusCode',
    'UBL-CR-543': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cbc:DocumentDescription',
    'UBL-CR-544': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cac:Attachment',
    'UBL-CR-545': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cac:ValidityPeriod',
    'UBL-CR-546': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cac:IssuerParty',
    'UBL-CR-547': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DocumentReference/cac:ResultOfVerification',
    'UBL-CR-548': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:PricingReference',
    'UBL-CR-549': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:OriginatorParty',
    'UBL-CR-550': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Delivery',
    'UBL-CR-551': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:PaymentTerms',
    'UBL-CR-552': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cbc:ID',
    'UBL-CR-553': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cbc:PrepaidIndicator',
    'UBL-CR-554': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cbc:SequenceNumeric',
    'UBL-CR-555': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cbc:AccountingCostCode',
    'UBL-CR-556': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cbc:AccountingCost',
    'UBL-CR-557': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cbc:PerUnitAmount',
    'UBL-CR-558': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cac:TaxCategory',
    'UBL-CR-559': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cac:TaxTotal',
    'UBL-CR-560': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:AllowanceCharge/cac:PaymentMeans',
    'UBL-CR-561': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:TaxTotal',
    'UBL-CR-562': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:WithholdingTaxTotal',
    'UBL-CR-563': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:PackQuantity',
    'UBL-CR-564': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:PackSizeNumeric',
    'UBL-CR-565': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:CatalogueIndicator',
    'UBL-CR-566': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:HazardousRiskIndicator',
    'UBL-CR-567': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:AdditionalInformation',
    'UBL-CR-568': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:Keyword',
    'UBL-CR-569': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:BrandName',
    'UBL-CR-570': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cbc:ModelName',
    'UBL-CR-571': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:BuyersItemIdentification/cbc:ExtendedID',
    'UBL-CR-572': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:BuyersItemIdentification/cbc:BarcodeSymbologyID',
    'UBL-CR-573': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:BuyersItemIdentification/cac:PhysicalAttribute',
    'UBL-CR-574': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:BuyersItemIdentification/cac:MeasurementDimension',
    'UBL-CR-575': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:BuyersItemIdentification/cac:IssuerParty',
    'UBL-CR-576': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:SellersItemIdentification/cbc:ExtendedID',
    'UBL-CR-577': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:SellersItemIdentification/cbc:BarcodeSymbologyID',
    'UBL-CR-578': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:SellersItemIdentification/cac:PhysicalAttribute',
    'UBL-CR-579': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:SellersItemIdentification/cac:MeasurementDimension',
    'UBL-CR-580': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:SellersItemIdentification/cac:IssuerParty',
    'UBL-CR-581': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ManufacturersItemIdentification',
    'UBL-CR-582': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:StandardItemIdentification/cbc:ExtendedID',
    'UBL-CR-583': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:StandardItemIdentification/cbc:BarcodeSymbologyID',
    'UBL-CR-584': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:StandardItemIdentification/cac:PhysicalAttribute',
    'UBL-CR-585': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:StandardItemIdentification/cac:MeasurementDimension',
    'UBL-CR-586': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:StandardItemIdentification/cac:IssuerParty',
    'UBL-CR-587': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:CatalogueItemIdentification',
    'UBL-CR-588': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemIdentification',
    'UBL-CR-589': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:CatalogueDocumentReference',
    'UBL-CR-590': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ItemSpecificationDocumentReference',
    'UBL-CR-591': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:OriginCountry/cbc:Name',
    'UBL-CR-592': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:CommodityClassification/cbc:NatureCode',
    'UBL-CR-593': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:CommodityClassification/cbc:CargoTypeCode',
    'UBL-CR-594': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:CommodityClassification/cbc:CommodityCode',
    'UBL-CR-595': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:TransactionConditions',
    'UBL-CR-596': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:HazardousItem',
    'UBL-CR-597': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:Name',
    'UBL-CR-598': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:BaseUnitMeasure',
    'UBL-CR-599': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:PerUnitAmount',
    'UBL-CR-600': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:TaxExemptionReasonCode',
    'UBL-CR-601': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:TaxExemptionReason',
    'UBL-CR-602': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:TierRange',
    'UBL-CR-603': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cbc:TierRatePercent',
    'UBL-CR-604': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cac:TaxScheme/cbc:Name',
    'UBL-CR-605': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cac:TaxScheme/cbc:TaxTypeCode',
    'UBL-CR-606': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cac:TaxScheme/cbc:CurrencyCode',
    'UBL-CR-607': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ClassifiedTaxCategory/cac:TaxScheme/cac:JurisdictionRegionAddress',
    'UBL-CR-608': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:ID',
    'UBL-CR-609': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:NameCode',
    'UBL-CR-610': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:TestMethod',
    'UBL-CR-611': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:ValueQuantity',
    'UBL-CR-612': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:ValueQualifier',
    'UBL-CR-613': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:ImportanceCode',
    'UBL-CR-614': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cbc:ListValue',
    'UBL-CR-615': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cac:UsabilityPeriod',
    'UBL-CR-616': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cac:ItemPropertyGroup',
    'UBL-CR-617': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cac:RangeDimension',
    'UBL-CR-618': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:AdditionalItemProperty/cac:ItemPropertyRange',
    'UBL-CR-619': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ManufacturerParty',
    'UBL-CR-620': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:InformationContentProviderParty',
    'UBL-CR-621': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:OriginAddress',
    'UBL-CR-622': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:ItemInstance',
    'UBL-CR-623': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:Certificate',
    'UBL-CR-624': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Item/cac:Dimension',
    'UBL-CR-625': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cbc:PriceChangeReason',
    'UBL-CR-626': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cbc:PriceTypeCode',
    'UBL-CR-627': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cbc:PriceType',
    'UBL-CR-628': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cbc:OrderableUnitFactorRate',
    'UBL-CR-629': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cbc:ValidityPeriod',
    'UBL-CR-630': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cbc:PriceList',
    'UBL-CR-632': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:ID',
    'UBL-CR-633': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:AllowanceChargeReasonCode',
    'UBL-CR-634': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:AllowanceChargeReason',
    'UBL-CR-635': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:MultiplierFactorNumeric',
    'UBL-CR-636': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:PrepaidIndicator',
    'UBL-CR-637': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:SequenceNumeric',
    'UBL-CR-638': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:AccountingCostCode',
    'UBL-CR-639': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:AccountingCost',
    'UBL-CR-640': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cbc:PerUnitAmount',
    'UBL-CR-641': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cac:TaxCategory',
    'UBL-CR-642': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cac:TaxTotal',
    'UBL-CR-643': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:AllowanceCharge/cac:PaymentMeans',
    'UBL-CR-644': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:Price/cac:PricingExchangeRate',
    'UBL-CR-645': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:DeliveryTerms',
    'UBL-CR-646': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:SubInvoiceLine',
    'UBL-CR-647': '(cac:InvoiceLine|cac:CreditNoteLine)/cac:ItemPriceExtension',
    'UBL-CR-648': 'cbc:CustomizationID/@schemeID',
    'UBL-CR-649': 'cbc:ProfileID/@schemeID',
    'UBL-CR-650': 'cbc:ID/@schemeID',
    'UBL-CR-651': 'cbc:SalesOrderID/@schemeID',
    'UBL-CR-652': '//cac:PartyTaxScheme/cbc:CompanyID/@schemeID',
    'UBL-CR-653': 'cac:PaymentMeans/cbc:PaymentID/@schemeID',
    'UBL-CR-654': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cbc:ID/@schemeID',
    'UBL-CR-655': 'cac:PaymentMeans/cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cbc:ID/@schemeID',
    'UBL-CR-656': 'cbc:InvoiceTypeCode/@listID',
    'UBL-CR-657': 'cbc:DocumentCurrencyCode/@listID',
    'UBL-CR-658': 'cbc:TaxCurrencyCode/@listID',
    'UBL-CR-659': 'cac:AdditionalDocumentReference/cbc:DocumentTypeCode/@listID',
    'UBL-CR-660': '//cac:Country/cbc:IdentificationCode/@listID',
    'UBL-CR-661': 'cac:PaymentMeans/cbc:PaymentMeansCode/@listID',
    'UBL-CR-662': '//cbc:AllowanceChargeReasonCode/@listID',
    'UBL-CR-663': '//@unitCodeListID',
    'UBL-CR-664': '//cac:FinancialInstitution',
    'UBL-CR-667': '//cac:BuyersItemIdentification/cbc:ID/@schemeID',
    'UBL-CR-668': '//cac:SellersItemIdentification/cbc:ID/@schemeID',
    'UBL-CR-669': '//cac:Price/cac:AllowanceCharge/cbc:AllowanceChargeReasonCode',
    'UBL-CR-670': '//cac:Price/cac:AllowanceCharge/cbc:AllowanceChargeReason',
    'UBL-CR-671': '//cac:Price/cac:AllowanceCharge/cbc:MultiplierFactorNumeric',
    'UBL-CR-672': 'cbc:CreditNoteTypeCode/@listID',
    'UBL-CR-674': '//cbc:PrimaryAccountNumberID/@schemeID',
    'UBL-CR-675': '//cac:CardAccount/cbc:NetworkID/@schemeID',
    'UBL-CR-676': '//cac:PaymentMandate/cbc:ID/@schemeID',
    'UBL-CR-677': '//cac:PaymentMandate/cac:PayerFinancialAccount/cbc:ID/@schemeID',
    'UBL-CR-678': '//cac:TaxCategory/cbc:ID/@schemeID',
    'UBL-CR-679': '//cac:ClassifiedTaxCategory/cbc:ID/@schemeID',
    'UBL-CR-680': '//cac:PaymentMeans/cac:PayerFinancialAccount',
    'UBL-CR-681': 'cac:PaymentMeans/cbc:InstructionNote',
    'UBL-CR-682': 'cac:Delivery/cac:DeliveryAddress',
    'UBL-DT-08': '//@schemeName',
    'UBL-DT-09': '//@schemeAgencyName',
    'UBL-DT-10': '//@schemeDataURI',
    'UBL-DT-11': '//@schemeURI',
    'UBL-DT-12': '//@format',
    'UBL-DT-13': '//@unitCodeListIdentifier',
    'UBL-DT-14': '//@unitCodeListAgencyIdentifier',
    'UBL-DT-15': '//@unitCodeListAgencyName',
    'UBL-DT-16': '//@listAgencyName',
    'UBL-DT-17': '//@listName',
    'UBL-DT-19': '//@languageID',
    'UBL-DT-20': '//@listURI',
    'UBL-DT-21': '//@listSchemeURI',
    'UBL-DT-22': '//@languageLocaleID',
    'UBL-DT-23': '//@uri',
    'UBL-DT-24': '//@currencyCodeListVersionID',
    'UBL-DT-25': '//@characterSetCode',
    'UBL-DT-26': '//@encodingCode',
    'UBL-DT-27': '//@schemeAgencyID',
    'UBL-DT-28': '//@listAgencyID',
}

AT_MOST_ONE = {
    'UBL-SR-33': ('cac:AdditionalDocumentReference',
                  'cbc:DocumentDescription'),
    'UBL-SR-25': ('cac:Delivery',
                  'cac:DeliveryParty/cac:PartyName/cbc:Name'),
    'UBL-SR-30': ('cac:AllowanceCharge[cbc:ChargeIndicator = false()]',
                  'cbc:AllowanceChargeReason'),
    'UBL-SR-31': ('cac:AllowanceCharge[cbc:ChargeIndicator = true()]',
                  'cbc:AllowanceChargeReason'),
    'UBL-SR-01': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:ContractDocumentReference/cbc:ID'),
    'UBL-SR-02': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:ReceiptDocumentReference/cbc:ID'),
    'UBL-SR-03': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:DespatchDocumentReference/cbc:ID'),
    'UBL-SR-05': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:PaymentTerms/cbc:Note'),
    'UBL-SR-08': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:InvoicePeriod'),
    'UBL-SR-09': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationName'),
    'UBL-SR-10': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingSupplierParty/cac:Party/cac:PartyName/cbc:Name'),
    'UBL-SR-11': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyID'),
    'UBL-SR-14': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyLegalForm'),
    'UBL-SR-15': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:RegistrationName'),
    'UBL-SR-16': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingCustomerParty/cac:Party/cac:PartyIdentification/cbc:ID'),
    'UBL-SR-17': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingCustomerParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyID'),
    'UBL-SR-24': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:Delivery'),
    'UBL-SR-39': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:ProjectReference/cbc:ID'),
    'UBL-SR-40': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:AccountingCustomerParty/cac:Party/cac:PartyName/cbc:Name'),
    'UBL-SR-45': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:PaymentMeans/cbc:PaymentDueDate'),
    'UBL-SR-49': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:InvoicePeriod/cbc:DescriptionCode'),
    'UBL-SR-54': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:PaymentMeans/cac:CardAccount'),
    'UBL-SR-55': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:PaymentMeans/cac:PaymentMandate'),
    'UBL-SR-56': ('/ubl:Invoice | /cn:CreditNote',
                  'cac:OriginatorDocumentReference/cbc:ID'),
    'UBL-SR-34': ('cac:InvoiceLine | cac:CreditNoteLine',
                  'cbc:Note'),
    'UBL-SR-35': ('cac:InvoiceLine | cac:CreditNoteLine',
                  'cac:OrderLineReference/cbc:LineID'),
    'UBL-SR-36': ('cac:InvoiceLine | cac:CreditNoteLine',
                  'cac:InvoicePeriod'),
    'UBL-SR-37': ('cac:InvoiceLine | cac:CreditNoteLine',
                  'cac:Price/cac:AllowanceCharge/cbc:Amount'),
    'UBL-SR-50': ('cac:InvoiceLine | cac:CreditNoteLine',
                  'cac:Item/cbc:Description'),
    'UBL-SR-52': ('cac:InvoiceLine | cac:CreditNoteLine',
                  'cac:DocumentReference'),
    'UBL-SR-26': ('cac:PaymentMeans',
                  'cbc:PaymentID'),
    'UBL-SR-27': ('cac:PaymentMeans',
                  'cbc:PaymentMeansCode'),
    'UBL-SR-28': ('cac:PaymentMeans',
                  'cac:PaymentMandate/cbc:ID'),
    'UBL-SR-06': ('cac:BillingReference',
                  'cac:InvoiceDocumentReference'),
    'UBL-SR-22': ('cac:TaxRepresentativeParty',
                  'cac:PartyName/cbc:Name'),
    'UBL-SR-23': ('cac:TaxRepresentativeParty',
                  'cac:PartyTaxScheme/cbc:CompanyID'),
    'UBL-SR-32': ('cac:TaxSubtotal',
                  'cac:TaxCategory/cbc:TaxExemptionReason'),
}
